{% set version = "2.29.3" %}
{% set gomodule = "github.com/errata-ai/vale" %}
{% set min_go = ">=1.20" %}

package:
  name: vale
  version: {{ version }}

source:
  folder: src/{{ gomodule }}
  url: https://{{ gomodule }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 660c1494db19bf7a0a692e83a3585c9ae30893c37f38436b012ccd66eaf839fa

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('go-cgo') }}  # [not osx]
    - go-cgo {{ min_go }}  # [not osx]
    - cgo {{ min_go }}  # [osx]
    - posix  # [win]
    - go-licenses
  host: []
  run: []

test:
  requires:
    - m2-grep  # [win]
  commands:
    - vale --version
    - vale --help
    - vale --version | grep -iE "{{ version.replace(".", "\.") }}"

about:
  home: https://vale.sh
  license: MIT
  license_family: MIT
  license_file:
    - src/{{ gomodule }}/LICENSE
    - license-files/
  summary: A syntax-aware linter for prose built with speed and extensibility in mind.
  dev_url: https://{{ gomodule }}
  doc_url: https://vale.sh/docs

extra:
  recipe-maintainers:
    - bollwyvl
