# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "3.13.0"
  go_min: "1.25.3"
  compiler_stack: ${{ "" if unix else "m2w64_" }}

package:
  name: vale
  version: ${{ version }}

source:
  url: https://github.com/errata-ai/vale/archive/refs/tags/v${{ version }}.tar.gz
  sha256: a6811e19c0ca8fc453da98238c2ffc7c5d5d1e77346d72d24fd47c09302fd7c0
  target_directory: src/github.com/errata-ai/vale
  patches:
    - 0000-use-conda-prefix.patch

build:
  number: 0
  script:
    file: build-vale

requirements:
  build:
    - ${{ compiler("go-cgo") }}
    - ${{ compiler(compiler_stack ~ "c") }}
    - ${{ compiler(compiler_stack ~ "cxx") }}
    - ${{ stdlib(compiler_stack ~ "c") }}
    - go >=${{ go_min }}
    - go-licenses

tests:
  - script:
      - vale --version
      - vale --help
      - if: win
        then: vale --version | findstr "${{ version | replace(".", "\\.") }}"
        else: vale --version | grep -iE "${{ version | replace(".", "\\.") }}"
      - vale ls-dirs
      - if: unix
        then:
          - mkdir -p "${CONDA_PREFIX}/share/vale/styles"
          - vale ls-dirs | grep "${CONDA_PREFIX}/share"
          - mkdir -p "${CONDA_PREFIX}/etc/vale"
          - touch "${CONDA_PREFIX}/etc/vale/.vale.ini"
          - vale ls-dirs | grep "${CONDA_PREFIX}/etc"
        else:
          - md "%CONDA_PREFIX%\share\vale\styles"
          - md "%CONDA_PREFIX%\etc\vale"
          - echo "TODO" >> "%CONDA_PREFIX%\etc\vale\.vale.ini"
      - vale ls-dirs

about:
  license: MIT
  license_file:
    - src/github.com/errata-ai/vale/LICENSE
    - license-files/
  summary: A syntax-aware linter for prose built with speed and extensibility in mind.
  homepage: https://vale.sh
  repository: https://github.com/errata-ai/vale
  documentation: https://vale.sh/docs

extra:
  recipe-maintainers:
    - bollwyvl
