# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "3.14.0"
  go_min: "1.25.3"
  go_mod: github.com/errata-ai/vale
  go_build: go build -v --buildmode=pie -trimpath -modcacherw -ldflags "-s -w -X main.version=${{ version }}"
  go_bin: ${{ "$PREFIX/bin/$PKG_NAME" if unix else "%PREFIX%\\bin\\%PKG_NAME%.exe" }}
  go_mod_xz: github.com/xi2/xz
  go_mod_ts_julia: github.com/jdkato/go-tree-sitter-julia/julia
  license_ignore: ${{ go_mod_xz }} ${{ go_mod_ts_julia }} ${{ go_mod }}
  var_src_dir: ${{ "$SRC_DIR" if unix else "%PREFIX%" }}

recipe:
  name: vale
  version: ${{ version }}

source:
  - url: https://${{ go_mod }}/archive/refs/tags/v${{ version }}.tar.gz
    sha256: fcc7177d2715283eede6482c80cdba1aa385cf8ea6046de2efabb6a068a6929e
    target_directory: src/${{ go_mod }}
    patches:
      - 0000-use-conda-prefix.patch
  - url: https://raw.githubusercontent.com/xi2/xz/refs/heads/master/LICENSE
    sha256: 5c640056d513f276d56635af7a0bed81cb7eac02a31b6e56d40c416557a8d8ce
    target_directory: license-files-manual/${{ go_mod_xz }}

build:
  number: 0

outputs:
  - package:
      name: vale
    build:
      script:
        env:
          GOPATH: ${{ var_src_dir }}
        content:
          - export
          - cd src/${{ go_mod }}
          - ${{ go_build }} -o "${{ go_bin }}" ./cmd/vale
          - |-
            go-licenses save ./cmd/vale --save_path "${{ var_src_dir }}/license-files"
              {%- for i in license_ignore | split %} --ignore=${{ i }}{% endfor %}

    requirements:
      build:
        - ${{ compiler("go-cgo") }}
        - go-licenses
        - go >=${{ go_min }}
        - if: unix
          then:
            - ${{ compiler("c") }}
            - ${{ compiler("cxx") }}
            - ${{ stdlib("c") }}
          else:
            - ${{ compiler("m2w64_c") }}
            - ${{ compiler("m2w64_cxx") }}
            - ${{ stdlib("m2w64_c") }}
    tests:
      - script:
          - vale --version
          - vale --help
          - vale --version | ${{ "grep -iE" if unix else "findstr" }} "${{ version | replace(".", "\\.") }}"
          - vale ls-dirs
          - if: unix
            then:
              - mkdir -p "${CONDA_PREFIX}/share/vale/styles"
              - vale ls-dirs | grep "${CONDA_PREFIX}/share"
              - mkdir -p "${CONDA_PREFIX}/etc/vale"
              - touch "${CONDA_PREFIX}/etc/vale/.vale.ini"
              - vale ls-dirs | grep "${CONDA_PREFIX}/etc"
            else:
              - md "%CONDA_PREFIX%\share\vale\styles"
              - md "%CONDA_PREFIX%\etc\vale"
              - echo "TODO" >> "%CONDA_PREFIX%\etc\vale\.vale.ini"
          - vale ls-dirs

about:
  license: MIT
  license_file:
    - src/${{ go_mod }}/LICENSE
    - license-files/
    - license-files-manual/
  summary: A syntax-aware linter for prose built with speed and extensibility in mind.
  homepage: https://vale.sh
  repository: https://${{ go_mod }}
  documentation: https://vale.sh/docs

extra:
  feedstock-name: vale
  recipe-maintainers:
    - bollwyvl
