build_platform:
  osx_arm64: osx_64
conda_build:
  error_overlinking: true
conda_build_tool: rattler-build
conda_forge_output_validation: true
conda_install_tool: pixi
github:
  branch_name: main
  tooling_branch_name: main
shellcheck:
  enabled: true
test: native_and_emulated
